AL\RealEstateBundle\Entity\Owner:
  type: entity
  table: owner
  id:
    id:
      type: integer
      generator: {strategy: AUTO}
  fields:
    name:
      type: string
      length: 255
    email:
      type: string
      length: 255
    phone_number:
      type: integer
    created_at:
      type: datetime
    token:
      type: string
      length: 255
      unique: true
  oneTo Many:
    real_estate_objects:
      targetEntity: RealEstate
      mappedBy: owner
  lifecycleCallbacks:
      prePersist: [ setCreatedAtValue ]