AL\RealEstateBundle\Entity\Owner:
  type: entity
  table: owner
  id:
    id:
      type: integer
      generator: {strategy: AUTO}
  fields:
    name:
      type: string
      length: 255
    email:
      type: string
      length: 255
    phone_number:
      type: integer
    token:
      type: string
      length: 255
      unique: true
  oneTo Many:
      owners:
          targetEntity: RealEstate
          mappedBy: owner