
AL\RealEstateBundle\Entity\RealEstate:
  type: entity
  table: real_estate
  id:
    id:
      type: integer
      generator: {strategy: AUTO}
  fields:
                        address:
                          type: string
                          length: 255
                        price:
                          type: float
                        desc:
                          type: text
                          length: 500
                          nullable: true
    is_public:
      type: boolean
      nullable: true
    is_activated:
      type: boolean
      nullable: true
    latitude:
      type: float
      nullable: true
    longitude:
      type: float
      nullable: true
    url:
      type: string
      length: 255
      nullable: true
    expires_at:
      type: datetime
    created_at:
      type: datetime
    updated_at:
      type: datetime
      nullable: true
  manyToOne:
    category:
      targetEntity: RealEstateCategory
      inversedBy: real_estate_objects
      joinColumn:
        name: category_id
        referencedColumnName: id