AL\RealEstateBundle\Entity\User:
  type: entity
  table: fos_user
  id:
    id:
      type: integer
      generator:
          strategy: AUTO
  fields:
#    username:
#      type: string
#      length: 255
#    password:
#      type: string
#      length: 255
    name:
      type: string
      length: 255
      nullable: true
#    email:
#      type: string
#      length: 255
    phone_number:
      type: integer
      nullable: true
    created_at:
      type: datetime
    token:
      type: string
      length: 255
      nullable: true
    githubID:
      type: string
      length: 255
      nullable: true
  oneToMany:
    real_estate_objects:
      targetEntity: RealEstate
      mappedBy: users
  lifecycleCallbacks:
      prePersist: [ setCreatedAtValue ]